apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-storage-pv
spec:
  storageClassName: "db"
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=3
  nfs:
    path: /export/k8s
    server: 192.168.10.25